//! Generated tests for the `signatures` subsection of the `analysis` spec.
//!
//! Regenerated by `ought generate` — hand edits will be overwritten.

#![allow(dead_code, clippy::all, non_snake_case, unused_imports)]
#![allow(dead_code, clippy::all)]
#![allow(non_snake_case, unused_imports)]

use std::path::{Path, PathBuf};
use std::time::Duration;

use chrono::Utc;
use ought_analysis::types::*;
use ought_analysis::{bisect, blame};
use ought_gen::generator::{GeneratedTest, Language};
use ought_run::runner::Runner;
use ought_run::{RunResult, TestDetails, TestResult, TestStatus};
use ought_spec::SpecGraph;
use ought_spec::types::*;

// =============================================================================
// (StubGenerator removed -- analysis functions no longer take a generator)
// =============================================================================

// =============================================================================
// Helper: mock Runner for tests that need a Runner trait object
// =============================================================================

struct StubRunner;
impl Runner for StubRunner {
    fn run(&self, _: &[GeneratedTest], _: &Path) -> anyhow::Result<RunResult> {
        Ok(RunResult {
            results: vec![],
            total_duration: Duration::ZERO,
        })
    }
    fn is_available(&self) -> bool {
        true
    }
    fn name(&self) -> &str {
        "stub"
    }
}

/// blame() function exists with the expected signature.
/// It takes (&ClauseId, &SpecGraph, &RunResult) and returns Result<BlameResult>.
#[test]
fn test_analysis__signatures__blame_function_exists() {
    let _fn_ptr: fn(&ClauseId, &SpecGraph, &RunResult) -> anyhow::Result<BlameResult> =
        blame::blame;
}

/// bisect() function exists with the expected signature.
/// It takes (&ClauseId, &SpecGraph, &dyn Runner, &BisectOptions) and returns Result<BisectResult>.
#[test]
fn test_analysis__signatures__bisect_function_exists() {
    let _fn_ptr: fn(
        &ClauseId,
        &SpecGraph,
        &dyn Runner,
        &bisect::BisectOptions,
    ) -> anyhow::Result<BisectResult> = bisect::bisect;
}
