/// MUST be agnostic to which LLM provider generates the test code
#[test]
fn test_ought__llm_agnostic__must_be_agnostic_to_which_llm_provider_generates_the_test_code() {
    use std::path::PathBuf;
    use ought_gen::context::GenerationContext;
    use ought_gen::generator::{GeneratedTest, Generator, Language};
    use ought_gen::providers::{parse_batch_response, BATCH_MARKER};
    use ought_gen::generator::ClauseGroup;
    use ought_spec::types::{Clause, ClauseId, Keyword, Severity, SourceLocation};

    // Any two providers implementing Generator must produce GeneratedTest values with
    // the same shape — provider identity is not encoded in the output type.
    struct ProviderA;
    struct ProviderB;

    fn make_generated(clause: &Clause, tag: &str) -> GeneratedTest {
        GeneratedTest {
            clause_id: clause.id.clone(),
            code: format!("// generated by {tag}\n#[test]\nfn test_x() {{ assert!(true); }}"),
            language: Language::Rust,
            file_path: PathBuf::from("x_test.rs"),
        }
    }

    impl Generator for ProviderA {
        fn generate(&self, clause: &Clause, _ctx: &GenerationContext) -> anyhow::Result<GeneratedTest> {
            Ok(make_generated(clause, "provider_a"))
        }
    }
    impl Generator for ProviderB {
        fn generate(&self, clause: &Clause, _ctx: &GenerationContext) -> anyhow::Result<GeneratedTest> {
            Ok(make_generated(clause, "provider_b"))
        }
    }

    let clause = Clause {
        id: ClauseId("ought::llm_agnostic::agnostic_clause".to_string()),
        keyword: Keyword::Must,
        severity: Severity::Required,
        text: "be agnostic to provider".to_string(),
        condition: None,
        otherwise: vec![],
        temporal: None,
        hints: vec![],
        source_location: SourceLocation { file: PathBuf::from("spec.ought.md"), line: 1 },
        content_hash: "abc".to_string(),
    };
    let ctx = GenerationContext {
        spec_context: None,
        source_files: vec![],
        schema_files: vec![],
        target_language: Language::Rust,
        verbose: false,
    };

    let a: Box<dyn Generator> = Box::new(ProviderA);
    let b: Box<dyn Generator> = Box::new(ProviderB);

    let result_a = a.generate(&clause, &ctx).expect("ProviderA must generate without error");
    let result_b = b.generate(&clause, &ctx).expect("ProviderB must generate without error");

    // Clause ID is preserved regardless of which provider generated the code
    assert_eq!(
        result_a.clause_id, result_b.clause_id,
        "GeneratedTest.clause_id must be identical regardless of which provider produced the code"
    );
    assert_eq!(
        result_a.language, result_b.language,
        "GeneratedTest.language must be identical regardless of provider"
    );

    // The batch response parser is provider-agnostic: it only looks for BATCH_MARKER
    // comments in the output, regardless of which LLM emitted them.
    let fake_batch_output = format!(
        "{BATCH_MARKER} ought::llm_agnostic::agnostic_clause ===\n\
         #[test]\nfn test_agnostic() {{ assert!(true); }}\n"
    );
    let group = ClauseGroup {
        section_path: "LLM Agnostic".to_string(),
        clauses: vec![&clause],
        conditions: vec![],
    };
    let parsed = parse_batch_response(&fake_batch_output, &group, Language::Rust);
    assert_eq!(parsed.len(), 1, "batch parser must parse one test from provider-agnostic marker output");
    assert_eq!(
        parsed[0].clause_id,
        ClauseId("ought::llm_agnostic::agnostic_clause".to_string()),
        "parsed clause_id must match the marker, not the provider"
    );
}